# Generated by Django 4.2.5 on 2024-12-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_todolist_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
