# Generated by Django 4.0.3 on 2024-10-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='student_description',
            new_name='student_enrolment_no',
        ),
    ]
