# Generated by Django 4.0.3 on 2024-10-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_student_description_userlist_student_enrolment_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlist',
            options={'ordering': ['student_name'], 'verbose_name': 'User List', 'verbose_name_plural': 'User Lists'},
        ),
    ]
